const sanitizeNetworkApiKey = (apiKey: string) => apiKey.replace(/[^a-zA-Z0-9]/g, '_');

/** LRUD node id for a dynamic "Network API" filter button (matches `createNavMap` / toolbar). */
export const networkApiFilterNavId = (apiKey: string) =>
  `DEBUG_UI_MODAL_DEBUG_MODE_NETWORK_API_${sanitizeNetworkApiKey(apiKey)}`;

/** Key into the toolbar `nav` map for a dynamic Network API filter. */
export const networkApiFilterNavMapKey = (apiKey: string) =>
  `DEBUG_MODE_NETWORK_API_${sanitizeNetworkApiKey(apiKey)}`;

export const DEBUG_UI_MODAL = {
  CONTAINER: 'DEBUG_UI_MODAL_CONTAINER',
  QUICK_ACTIONS_CONTAINER: 'DEBUG_UI_MODAL_QUICK_ACTIONS_CONTAINER',
  DEBUG_MODE_CONTAINER: 'DEBUG_UI_MODAL_DEBUG_MODE_CONTAINER',
  DEBUG_MODE_NETWORK_CONTAINER: 'DEBUG_UI_MODAL_DEBUG_MODE_NETWORK_CONTAINER',
  DEBUG_MODE_NETWORK_API_CONTAINER: 'DEBUG_UI_MODAL_DEBUG_MODE_NETWORK_API_CONTAINER',
  CANCEL_BUTTON: 'DEBUG_UI_MODAL_CANCEL_BUTTON',
  FOCUS_MAIN_APP_BUTTON: 'DEBUG_UI_MODAL_FOCUS_MAIN_APP_BUTTON',
  AUTO_SCROLL_TO_NEW_ENTRY_BUTTON: 'DEBUG_UI_MODAL_AUTO_SCROLL_TO_NEW_ENTRY_BUTTON',
  AUTO_REFRESH_BUTTON: 'DEBUG_UI_MODAL_AUTO_REFRESH_BUTTON',
  QUIT_DEBUGGER_BUTTON: 'DEBUG_UI_MODAL_QUIT_DEBUGGER_BUTTON',
  SWITCH_DEBUG_VIEW_BUTTON: 'DEBUG_UI_MODAL_SWITCH_DEBUG_VIEW_BUTTON',
  DEBUG_MODE_LOGS_BUTTON: 'DEBUG_UI_MODAL_DEBUG_MODE_LOGS_BUTTON',
  DEBUG_MODE_DEBUG_BUTTON: 'DEBUG_UI_MODAL_DEBUG_MODE_DEBUG_BUTTON',
  DEBUG_MODE_INFO_BUTTON: 'DEBUG_UI_MODAL_DEBUG_MODE_INFO_BUTTON',
  DEBUG_MODE_WARN_BUTTON: 'DEBUG_UI_MODAL_DEBUG_MODE_WARN_BUTTON',
  DEBUG_MODE_ERRORS_BUTTON: 'DEBUG_UI_MODAL_DEBUG_MODE_ERRORS_BUTTON',
  DEBUG_MODE_NETWORK_BUTTON: 'DEBUG_UI_MODAL_DEBUG_MODE_NETWORK_BUTTON',
  DEBUG_MODE_ALL_BUTTON: 'DEBUG_UI_MODAL_DEBUG_MODE_ALL_BUTTON',
  DEBUG_MODE_FETCH_XHR_BUTTON: 'DEBUG_UI_MODAL_DEBUG_MODE_FETCH_XHR_BUTTON',
  DEBUG_MODE_OTHER_NETWORK_BUTTON: 'DEBUG_UI_MODAL_DEBUG_MODE_OTHER_NETWORK_BUTTON',
  DEBUG_MODE_ALL_NETWORK_BUTTON: 'DEBUG_UI_MODAL_DEBUG_MODE_ALL_NETWORK_BUTTON',
  DEBUG_MODE_ALL_ANALYTICS_BUTTON: 'DEBUG_UI_MODAL_DEBUG_MODE_ALL_ANALYTICS_BUTTON',
  DEBUG_MODE_ENTRIES_LIST: 'DEBUG_UI_MODAL_DEBUG_MODE_ENTRIES_LIST',
  SETTINGS_CONTAINER: 'DEBUG_UI_MODAL_SETTINGS_CONTAINER',
  QUICK_KEY_SEQUENCE_BUTTON: 'DEBUG_UI_MODAL_QUICK_KEY_SEQUENCE_BUTTON',
  RECORDING_STATUS_CONTAINER: 'DEBUG_UI_MODAL_RECORDING_STATUS_CONTAINER',
  RECORD_LOG_BUTTON: 'DEBUG_UI_MODAL_RECORD_LOG_BUTTON',
  RECORD_DEBUG_BUTTON: 'DEBUG_UI_MODAL_RECORD_DEBUG_BUTTON',
  RECORD_INFO_BUTTON: 'DEBUG_UI_MODAL_RECORD_INFO_BUTTON',
  RECORD_WARN_BUTTON: 'DEBUG_UI_MODAL_RECORD_WARN_BUTTON',
  RECORD_ERROR_BUTTON: 'DEBUG_UI_MODAL_RECORD_ERROR_BUTTON',
  RECORD_NETWORK_TRAFFIC_BUTTON: 'DEBUG_UI_MODAL_RECORD_NETWORK_TRAFFIC_BUTTON',
  FLUSH_CONTAINER: 'DEBUG_UI_MODAL_FLUSH_CONTAINER',
  FLUSH_LOG_BUTTON: 'DEBUG_UI_MODAL_FLUSH_LOG_BUTTON',
  FLUSH_DEBUG_BUTTON: 'DEBUG_UI_MODAL_FLUSH_DEBUG_BUTTON',
  FLUSH_INFO_BUTTON: 'DEBUG_UI_MODAL_FLUSH_INFO_BUTTON',
  FLUSH_WARN_BUTTON: 'DEBUG_UI_MODAL_FLUSH_WARN_BUTTON',
  FLUSH_ERROR_BUTTON: 'DEBUG_UI_MODAL_FLUSH_ERROR_BUTTON',
  FLUSH_NETWORK_TRAFFIC_BUTTON: 'DEBUG_UI_MODAL_FLUSH_NETWORK_TRAFFIC_BUTTON',
} as const;

export default DEBUG_UI_MODAL;
